-- Config file for testing EF Core 

DROP TABLE IF EXISTS Blogs; 
CREATE TABLE IF NOT EXISTS Blogs (
    -- 
    BlogId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    Url VARCHAR(255)
);

DROP TABLE IF EXISTS Posts; 
CREATE TABLE IF NOT EXISTS Posts (
    PostId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Title VARCHAR(255),
    Content TEXT, 
    BlogId INTEGER
); 
